name: Harran
favicon: null
layout_spectrum: 0.1038142
typography_spectrum: 0.3996416
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fafafa'
    - '#9e9e9e'
    - '#4c4c4c'
    - '#333333'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
