layout_spectrum: 0.1038142
typography_spectrum: 0.3996416
color:
  saturation: 0.2936349
  brandStrength: 1
  lightness: 0.5878136
  brandColors:
    - '#161716'
    - '#FFFFFF'
    - '#C4BFB3'
    - '#5C5C5C'
    - '#9A764C'
  rhythmicContrast: 0.5390556
name: Harran
